<?php
use App\Core\Application;
use App\Core\Bootstrap;
?>

<!doctype html>
<html lang="cs-CZ">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= isset(Bootstrap::$config['AplicationName'])?Bootstrap::$config['AplicationName'] . ' | ':''?><?= isset($title)? $title : ''?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/style.css" />

</head>
<body>
    <nav class="navbar navbar-expand-lg shadow bg-white">
        <div class="container-fluid">
            <a class="navbar-brand">
                <!-- <img src="https://getbootstrap.com/docs/5.2/assets/brand/bootstrap-logo.svg" alt="Logo" width="30" height="24" class="d-inline-block align-text-top"> -->
                <?= isset(Bootstrap::$config['AplicationName'])?Bootstrap::$config['AplicationName']:'' ?>
            </a>
                
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link " aria-current="page" href="/">Home</a>
                    </li>
                    <?php if(Application::isAdmin()): ?>
                    <li class="nav-item">
                        <a class="nav-link " aria-current="page" href="/users">Uživatelé</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/insureds">Pojištěnci</a>
                    </li>
                    <?php endif; ?>
                    <li class="nav-item">
                        <a class="nav-link" href="/insurances">Pojištění</a>
                    </li>
                    <?php if(Application::isAdmin()): ?>
                    <li class="nav-item">
                        <a class="nav-link" href="/products">Produkty</a>
                    </li>
                    <?php endif; ?>
                </ul>

                <ul class="navbar-nav">
                    <?php if (!isset($_SESSION['user'])): ?>
                    <li class="nav-item"><a href="/login" class="nav-link">Přihlásit</a></li>
                    <li class="nav-item"><a href="/register" class="nav-link">Registrovat</a></li>
                    <?php elseif (isset($_SESSION['user'])): ?>
                    <li class="nav-item">
                        <a href="/user/<?= $user_id ?>" class="nav-link"><?= (Application::isAdmin()) ? '<span class="badge rounded-pill text-bg-danger">Admin</span>': null ?> <?= "$user_firstname $user_lastname" ?>
                        </a>
                    </li>
                    <li class="nav-item"><a href="/logout" class="nav-link">Odhlásit</a></li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </nav>


    <?php if (Application::$app->session->getFlash('success')): ?>
        <div class="container auto-close-alert alert alert-success alert-dismissible fade show px-4 mt-4" role="alert">
            <?= Application::$app->session->getFlash('success') ?>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>

    <?php elseif (Application::$app->session->getFlash('warning')): ?>
        <div class="container auto-close-alert alert alert-warning alert-dismissible fade show px-4 mt-4" role="alert">
            <?= Application::$app->session->getFlash('warning') ?>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <?php endif; ?>

    <div id="content-wrapper" class="container d-flex flex-column px-4 pt-2 my-5">
        <article>
            [{content}]
        </article>
        
    </div>

    <footer class="d-flex flex-wrap shadow justify-content-between bg-white align-items-center py-3 border-top">
        <div class="container col-md d-flex align-items-center">
            <span class="mb-3 mb-md-0 text-muted">© 2022 <?= Bootstrap::$config['AplicationName'] ?></span>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    <script src="/js/main.js" type="text/javascript"></script>

    <script src="https://unpkg.com/@popperjs/core@2"></script>
    <script src="https://unpkg.com/feather-icons"></script>
    <script>
        const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
        const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))

        feather.replace()
    </script>
</body>
</html>