<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-5 border-bottom">
    <h1 class="h2"><?= $title ?></h1>
</div>




<div class="row">
    <div class="col">
        <div class="card shadow">
            <div class="card-body">
                <form class="row g-2 p-4" method="post">
                    <div class="col-md-6 form-floating">
                        <input type="text" name="user_firstname" id="floatingInput" placeholder="Jméno" value="<?= (isset($user_firstname)) ? $user_firstname : null ?>" class="form-control form-control-lg" required/>
                        <label class="form-label">Jméno</label>
                    </div>

                    <div class="col-md-6 form-floating">
                        <input type="text" name="user_lastname" id="floatingInput" placeholder="Příjmení" value="<?= (isset($user_lastname)) ? $user_lastname : null ?>" class="form-control form-control-lg" required/>
                        <label class="form-label">Příjmení</label>
                    </div>

                    <div class="col-md-4 form-floating">
                        <input type="email" name="user_email" id="floatingInput" placeholder="Email" value="<?= (isset($user_email)) ? $user_email : null ?>" class="form-control form-control-lg" required/>
                        <label class="form-label">Email</label>
                    </div>

                    <div class="col-md-4 form-floating">
                        <input type="tel" name="user_telephone" id="floatingInput" placeholder="Telefoní číslo" value="<?= (isset($user_telephone)) ? $user_telephone : null ?>" class="form-control form-control-lg" required/>
                        <label class="form-label">Telefoní číslo</label>
                    </div>

                    <div class="col-md-4 form-floating">
                        <input type="date" name="user_birthdate" id="floatingInput" placeholder="Datum narození" value="<?= (isset($user_birthdate)) ? $user_birthdate : null ?>" class="pb-05 form-control form-control" required/>
                        <label class="form-label">Datum narození</label>
                    </div>

                    <div class="col-md-12 form-floating">
                        <input type="text" name="user_address" id="floatingInput" placeholder="Ulice a číslo popisné" value="<?= (isset($user_address)) ? $user_address : null ?>" class="form-control form-control-lg" required/>
                        <label class="form-label">Ulice a číslo popisné </label>
                    </div>

                    <div class="col-md-6 form-floating">
                        <input type="text" name="user_city" placeholder="Město" value="<?= (isset($user_city)) ? $user_city : null ?>" class="form-control form-control-lg" required/>
                        <label class="form-label">Město</label>
                    </div>

                    <div class="col-md-6 form-floating">
                        <input type="text" name="user_psc" id="floatingInput" placeholder="PSČ" value="<?= (isset($user_psc)) ? $user_psc : null ?>" class="form-control form-control-lg" required/>
                        <label class="form-label">PSČ</label>
                    </div>

                    <?php if(\App\Core\Application::isAdmin()): ?>
                        <div class="pt-5">
                            <div class="form-floating">
                                <select class="form-select form-select-lg mb-3" name="user_type" aria-label="Aktivní">
                                    <option <?= isset($user_type) && ($user_type == 1)? 'selected': null ?> value="1">Pojištěnec</option>
                                    <option <?= isset($user_type) && ($user_type == 0)? 'selected': null ?> value="0">Admin</option>
                                </select>
                                <label for="floatingSelect">Typ uživatele</label>
                            </div>
                        </div>
                    <?php endif; ?>

                    <div class="d-flex justify-content-center col-12 pt-4">
                        <button type="submit" class="btn btn-primary">Uložit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
