<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-5 border-bottom">
    <h1 class="h2"><?= $title ?></h1>
    <div class="btn-toolbar mb-2 mb-md-0">

        <?php if (\App\Core\Application::isAdmin()): ?>
        <div class="btn-group me-2">
            <a class="btn btn-warning" href="/insurance/<?= $insurance_id ?>/edit" role="button">Změna údajů</a>
        </div>
        <?php endif; ?>

    </div>
</div>

<div class="row">
    <div class="col">
        <div class="card shadow">
            <div class="card-body p-4">
                <div class="row">
                    <div class="col-4">
                        <img src="https://img.icons8.com/bubbles/300/null/invoice.png" class="img-radius" alt="User-Profile-Image">
                    </div>

                    <div class="col-8">
                        <div class="row pt-4">
                            <div class="col-12"><h3> <?= $product_name ?></h3></div>
                        </div>

                        <div class="row pt-4">
                            <div class="col-6"><strong>Pojištěnec:</strong> <?= $user_firstname . " " .  $user_lastname ?></div>
                            <div class="col-6"><strong>Částka:</strong>  <?= \App\Core\Helper::amount($insurance_sum) ?></div>
                        </div>

                        <div class="row">
                            <div class="col-6"><strong>Platné od:</strong> <?=  \App\Core\Helper::dateIsSet(\App\Core\Helper::date(($insurance_start_date)))?></div>
                            <div class="col-6"><strong>Platné do:</strong>  <?=  \App\Core\Helper::dateIsSet(\App\Core\Helper::date(($insurance_end_date)))?></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

