<div class=" form-signin d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-5 border-bottom">
    <h1 class="h2">Přihlášení</h1>
</div>

<form class="form-signin row g-2" method="post">
    <div class="form-floating">
        <input type="text" name="login" placeholder="Email nebo telefoní číslo" value="<?= (isset($login)) ? $login : null ?>" id="floatingInput" class="form-control form-control-lg" />
        <label class="form-label">Email nebo telefoní číslo</label>
    </div>

    <div class="form-floating">
        <input type="password" name="password"  id="floatingInput" placeholder="Heslo" class="form-control form-control-lg" />
        <label class="form-label">Heslo</label>
    </div>


    <div class="d-flex justify-content-center col-12 pt-4">
        <button type="submit" class="btn btn-primary">Přihlásit se</button>
    </div>
</form>