<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-5 border-bottom">
    <h1 class="h2">Detail uživatele</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group me-2">
            <a class="btn btn-warning" href="/user/<?= $user_id ?>/edit" role="button">Změna údajů</a>
        </div>
    </div>
</div>
<p>Jméno: <?= $user_firstname . " " .  $user_lastname ?></p>
<p>Email: <?= $user_email ?></p>
<p>Datum narození: <?=  \App\Core\Helper::dateIsSet(\App\Core\Helper::date(($user_birthdate)))?></p>
<p>Věk: <?= \App\Core\Helper::dateToOld($user_birthdate)?></p>