<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-0 mb-4 border-bottom">
    <h2 class="h2"><?= $title ?></h2>

</div>

<div class="row">
    <div class="col-xl-4 col-md-6 mb-4">
        <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                            Pojištění celkem</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800"><?= $tot_count_insurances ?></div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xl-4 col-md-6 mb-4">
        <div class="card border-left-info shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Aktivních pojištění</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800"><?= $tot_active_insurances ?></div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Pending Requests Card Example -->
    <div class="col-xl-4 col-md-6 mb-4">
        <div class="card border-left-warning shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                            Celková hodnota pojištění</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800"><?= \App\Core\Helper::amount($tot_su_insurances) ?></div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-comments fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col">
        <div class="card shadow">

            <div class="card-body p-4">
                <h5 class="card-title pb-2">Brzy končící pojištění</h5>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">Název pojištění</th>
                            <th scope="col">Částka</th>
                            <th scope="col">Skončí za</th>
                            <th scope="col"></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($data['end_insurances'] as $value):?>
                        <tr>
                            <td class="col-7"><?= $value['product_name'] ?></td>
                            <td class="col-2"><?= \App\Core\Helper::amount($value['insurance_sum']) ?></td>
                            <td class="col-2"><?= \App\Core\Helper::productEnd($value['insurance_end_date']) ?></td>
                            <td class="col-1"><a class="btn btn-primary" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Zobrazit pojištění" href="/insurance/<?= $value['insurance_id'] ?>" role="button">
                                    <i data-feather="eye"></i>
                                </a></td>
                        </tr>
                        <?php endforeach; ?>

                        </tbody>
                    </table>
                </div>
                <a href="/insurances" class="btn btn-block btn-light">Zobrazit vše</a>
            </div>
        </div>
    </div>
</div>